#!/bin/bash
grep -ir "-" 0312_win_loss_player_data >> ../../Dealers_working_during_losses
awk -F , '{print $1,$2,$3,$4}' ../../Dealer_Analysis/Dealer_Schedules_0310/0312_Dealer_schedule >> ../../Dealers_working_during_losses

